### ISSUE TITLE
NBXplorer Can't find Parent Transaction

### ISSUE THREAD

**Issue by sigHash** [dgarage/NBXplorer#166]
I went from nbxplorer:2.0.0.0 to nbxplorer:2.0.0.15. 

I create a derivation scheme and use bitcoin-cli to send some coins to my address.
The balance changes and the transaction shows up. However,  when I try to fetch the parent transaction, nb returns null (which wan't the case before upgrade). 

I see the same behavior on testnet when I send coin from faucet to my address, that transaction doesn't get indexed. 

```
private async Task<Money> CalculateTransactionFeeAsync(Transaction transaction, BTCPayNetwork network)
        {
            Dictionary<uint256, Transaction> parentTransactions = new Dictionary<uint256, Transaction>();
            var parentHashes = transaction.Inputs.Select(i => i.PrevOut.Hash).ToHashSet();
            var explorer = ExplorerClientProvider.GetExplorerClient(network);
            var getTransactionAsyncs = parentHashes.Select(h => (Op: explorer.GetTransactionAsync(h), Hash: h)).ToList();
            foreach (var getTransactionAsync in getTransactionAsyncs)
            {
                var tx = (await getTransactionAsync.Op);
                if (tx == null)
                    throw new Exception($"Parent transaction {getTransactionAsync.Hash} not found");
                parentTransactions.Add(tx.Transaction.GetHash(), tx.Transaction);
            }

            var allParentCoins = parentTransactions.Values.SelectMany(p => p.Outputs.AsCoins()).ToArray();
            return transaction.GetFee(allParentCoins);
        }
```

**Comment by NicolasDorier** [comment]
This is by design. NBXplorer only remember transactions directly involving a derivation scheme that it tracks.

So if you track wallet A, and you receive transaction B sending money to A, you can't get the parents of transaction B. UNLESS transaction B involved another wallet tracked by NBXplorer.

This basically mean that you can't know the fees of a transaction whose inputs are not all owned by wallets tracked by NBXplorer.
