### ISSUE TITLE
Regression in `2.2.X`: Connection failure to `bitcoind` after `v2.1.58`

### ISSUE THREAD

**Issue by darosior** [dgarage/NBXplorer#354]
Along with the latest release of BTCPay, i tried updating NBXplorer to the latest version (`v2.2.20`). The update results in NBXplorer being unable to speak to `bitcoind`.
Note that i also tested with other `v2.2.x` versions.

The setup is as follows:
- a `bitcoind` user runs the `bitcoind` process.
- A `btcpay` user runs `NBXplorer`.
- Both are part of the `bitcoin` group.
- `bitcoind`'s cookie file is readable by the group `bitcoin`.
- In NBXplorer's config the entry `btc.rpc.cookiefile` is set to the path to `bitcoind`'s cookie file.

It's not due to a regression in the environment, as the user `btcpay` itself is able to use `bitcoin-cli`.

**Comment by farukterzioglu** [comment]
Since v2.2.5, absence of `whitelist` config in bitcoind is preventing connecting to the node. Kindly check #347 
It may be because of this or maybe from other problem. 

@darosior could you share logs from both NBXplorer and bitcoind at the time of problem.

**Comment by darosior** [comment]
Ok, it must be because of this. But for reasons already stated elsewhere (https://github.com/dgarage/NBXplorer/issues/347#issuecomment-1107954410) it's not reasonable to just whitelist localhost... Let me investigate if there is any way around doing that.

**Comment by NicolasDorier** [comment]
Closing this then: To be precise, the recommended are `noban` and `mempool`.

On the new backend, `mempool` isn't mandatory, what will happen is that NBX will be kicked the first connection, then reconnect and not retry.

It may be possible in theory that NBX relies on ZMQ instead of P2P, but I don't want to change something that has been working forever.
ZMQ libraries would also add a native dependency to NBXplorer, which I want to avoid.
