### ISSUE TITLE
Add `replacing` property to events

### ISSUE THREAD

**Issue by kallerosenbaum** [dgarage/NBXplorer#411]
I suggest adding `replacing` property to events. This would make users' lives easier and safer.

There are two issues with the `replacing` and `replacedBy` properties:

1. They aren't included (both are null) when you query specific transactions, e.g. `HTTP GET v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/{txId}`. If you have lots and lots of transactions for your derivation scheme, querying all transactions when you're only interested in one becomes really impractical.
2. They aren't included in `newtransaction` events (I guess `replacedBy` isn't applicable, but `repacing` certainly is)

For me, fixing issue 2 would be preferable, but if that's not possible, fixing 1 works too. Of course both would be great.

**Comment by NicolasDorier** [comment]
will take a look.

**Comment by NicolasDorier** [comment]
@kallerosenbaum so sadly, the way `v1/cryptos/{cryptoCode}/derivations/{derivationScheme}/transactions/` works is by querying all the transactions in memory and finding what is relpacing what. So even if you had one transaction, if you want 1, I'd need to take all from DB. This only concerned the `replacing` property.

I may be able to hack something for `replacedBy`, but I'd prefer not, this code is a bit messy. (only if you think you REALLY need it)

That said, I am adding it to `cryptos/{cryptoCode}/transactions/{txId}`, so that might be enough for you. (only `replacedBy`)

Btw, did you consider querying the postgres tables directly?
The schema is straightforward, so in some case it might be more performant and flexible for you.

**Comment by NicolasDorier** [comment]
Trying to add `replacing` to the event as well...

**Comment by NicolasDorier** [comment]
@kallerosenbaum I have another trouble: `replacing` should be an array rather than a single value. As a single transaction can replace sevaral other transaction.

**Comment by NicolasDorier** [comment]
Please review the two PRs documentation if that's all you need.

**Comment by kallerosenbaum** [comment]
I have reviewed now, only one question, on #413 . Thanks so much for your efforts!!!
